services:
  keepup.frontend:
    container_name: keepup.frontend
    image: keepup.frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

  keepup.backend:
    container_name: keepup.backend
    image: keepup.backend
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=keepup.postgres
      - DB_PORT=5432
      - DB_USER=keepup
      - DB_PASSWORD=keepup
      - DB_NAME=keepup
      - GIN_MODE=debug
    depends_on:
      keepup.postgres:
        condition: service_healthy

  keepup.postgres:
    container_name: keepup.postgres
    image: postgis/postgis:17-3.5
    restart: always
    environment:
      - POSTGRES_USER=keepup
      - POSTGRES_PASSWORD=keepup
      - POSTGRES_DB=keepup
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "keepup", "-d", "keepup"]
      interval: 5s
      timeout: 5s
      retries: 5

  keepup.postgres.admin:
    container_name: keepup.postgres.admin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@keepup.com
      - PGADMIN_DEFAULT_PASSWORD=keepup
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "5431:80"
    depends_on:
      keepup.postgres:
        condition: service_healthy
