FROM golang:1.24.5-alpine AS builder

WORKDIR /app

# Install git for go modules, ca-certificates for HTTPS requests
RUN apk add --no-cache git ca-certificates

# Install air
RUN go install github.com/air-verse/air@latest

# Copy go.mod and go.sum first (for faster rebuilds)
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy source code
COPY . .

# Set docker-entrypoint.sh as executable
RUN chmod +x docker-entrypoint.sh

# Expose port
EXPOSE 8080

# Set entrypoint
ENTRYPOINT [ "./docker-entrypoint.sh" ]

# Run the binary
CMD ["air"]
